version: 1
update_configs:
  # Update package.json
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
      include_scope: true
    allowed_updates:
      # Trigger only security updates for dependencies by default
      - match:
          dependency_type: "production"
          update_type: "security"
      # Trigger all updates for `seal-…` dependencies
      - match:
          dependency_name: "seal-*"
          update_type: "all"
      # Trigger all updates for `@sealsystems/…-` dependencies
      - match:
          dependency_name: "@sealsystems/*"
          update_type: "all"
      # Trigger NO updates for devDependencies! Would result in an endless loop!
    automerged_updates:
      # Auto-merge minor version updates for `seal-…` dependencies
      - match:
          dependency_name: "seal-*"
          update_type: "semver:minor"
      # Auto-merge minor version updates for `@sealsystems/…-` dependencies
      - match:
          dependency_name: "@sealsystems/*"
          update_type: "semver:minor"
