version: 1
update_configs:
  # Update package.json
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "chore"
      include_scope: true
    allowed_updates:
      # Trigger all updates for dependencies
      - match:
          dependency_type: "production"
          update_type: "all"
      # Trigger NO updates for devDependencies! Would result in an endless loop!
