version: 1
update_configs:
  # Update package.json
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    default_reviewers:
      - "seal-mis"
    commit_message:
      prefix: "chore"
      prefix_development: "no-release"
      include_scope: true
    allowed_updates:
      # Trigger all updates for dependencies by default
      - match:
          dependency_type: "direct"
          # NOTE: Allow only security updates for now in order to decrease GitHub Actions activity
          # update_type: "all"
          update_type: "security"
    ignored_updates:
      # Ignore our dev-modules for linting, testing, and releasing since our nightly
      # build-config update takes care of it
      - match:
          dependency_name: "@sealsystems/eslint-config-es"
      - match:
          dependency_name: "@sealsystems/mocha"
      - match:
          dependency_name: "@sealsystems/semantic-release"
    automerged_updates:
      # Auto-merge minor version updates for `seal-…` dependencies
      - match:
          dependency_name: "seal-*"
          update_type: "semver:minor"
      # Auto-merge minor version updates for `@sealsystems/…-` dependencies
      - match:
          dependency_name: "@sealsystems/*"
          update_type: "semver:minor"
      # Auto-merge all updates for devDependencies
      - match:
          dependency_type: "development"
          update_type: "all"
