name: Master

on:
  push:
    branches:
    - master
    # Ignore changes made by releases
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

env:
  LOG_LEVELS: fatal
  TLS_UNPROTECTED: world

jobs:
  Test-Linux:
    runs-on: ubuntu-18.04

    services:
      mongo:
        image: mongo:3.6.17
        ports:
        - 27017:27017
      consul:
        image: consul:0.9.3
        ports:
        - 8500:8500

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: 12.13.1

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-12.13.1-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run bot

  Release:
    needs:
    - Test-Linux

    runs-on: ubuntu-18.04

    env:
      GIT_AUTHOR_EMAIL: com.git@sealsystems.de
      GIT_AUTHOR_NAME: CI Build
      GIT_COMMITTER_EMAIL: com.git@sealsystems.de
      GIT_COMMITTER_NAME: CI Build
      # Use personal access token for creating releases on GitHub
      GITHUB_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
      # Use personal access token for publishing on GitHub Packages
      NPM_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        # Use personal access token for cloning (and later pushing) code
        token: ${{ secrets.GITHUB_CI_TOKEN }}

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        NODE_VERSION: ${{ env.NODE_VERSION }}

    - name: Cache Node.js modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Trigger release
      run: npm run release
